### ISSUE TITLE
Capture error responses as a metric and log rather than crash

### ISSUE THREAD

**Issue by mkhpalm** [terascope/teraslice-exporter#12]
When teraslice-exporter gets a bad response from teraslice-master it causes the exporter to crash. Ideally these events would be caught, logged, added to its own metrics instead of exiting the process.

Example log and crash 

```
> @0.2.0 start /app/source
> node dist/index.js
{
  "name": "teraslice_exporter",
  "terasliceUrl": "http://localhost:5678/",
  "hostname": "teraslice-foo-master-5c64d8c9f4-fvf6g",
  "pid": 19,
  "level": 50,
  "msg": "Error encountered getting terasliceStats: Error: Error getting http://localhost:5678/v1/cluster/controllers: HTTPError: Response code 500 (Internal Server Error)",
  "time": "2023-11-30T19:47:08.295Z",
  "v": 0
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.2.0 start: `node dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-11-30T19_47_08_318Z-debug.log
```

**Comment by godber** [comment]
Maybe one of these would be useful:

* https://grafana.com/docs/k6/latest/testing-guides/injecting-faults-with-xk6-disruptor/first-steps/
* https://chaos-mesh.org/docs/simulate-network-chaos-on-kubernetes/

**Comment by busma13** [comment]
How I set up xk6:
- Go here https://github.com/grafana/xk6-disruptor/releases and download the appropriate compressed binary from the assets section of the newest release. I used `xk6-disruptor-v0.3.10-darwin-arm64.tar.gz` since I'm on a Mac with an m2 chip.
- unzip the tarball with `tar -xzf <file name>`
- try to run the binary: `./xk6-disruptor-darwin-arm64 version` (yours may have a different name)
-  Mac will warn you that it may be unsafe. Follow the directions they give you to bypass this.
- run the binary again to make sure it works. 
```
k6 v0.46.0 ((devel), go1.19.13, darwin/arm64)
Extensions:
  github.com/grafana/xk6-disruptor v0.3.10, k6/x/disruptor [js]
```
- Make a script that creates a service disruptor. See the example here: https://k6.io/docs/javascript-api/xk6-disruptor/api/servicedisruptor/ or use this: 
```
import { ServiceDisruptor } from 'k6/x/disruptor';

export default function () {
    // Create a new disruptor that targets a service
    const disruptor = new ServiceDisruptor("teraslice-master","ts-dev1");

    // Disrupt the targets by injecting delays and faults into HTTP request for 30 seconds
    const fault = {
        // averageDelay: '500ms',
        errorRate: .1,
        errorCode: 500
    }
    disruptor.injectHTTPFaults(fault, "30s")
}
```
- `teraslice-master` is the k8s service we are disrupting and `ts-dev1` is the namespace.
- start teraslice in kind: `yarn k8s-env` from teraslice root directory
- run your service disruptor: `./xk6-disruptor-darwin-arm64 run myDisruptorScript.ts`
- start teraslice-exporter
- You should get a crash with a 500 error almost immediately. Adjust the `errorRate` to make it more or less frequent.
